# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.40
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

package Bayesian;
use base qw(Exporter);
use base qw(DynaLoader);
package Bayesianc;
bootstrap Bayesian;
package Bayesian;
@EXPORT = qw();

# ---------- BASE METHODS -------------

package Bayesian;

sub TIEHASH {
    my ($classname,$obj) = @_;
    return bless $obj, $classname;
}

sub CLEAR { }

sub FIRSTKEY { }

sub NEXTKEY { }

sub FETCH {
    my ($self,$field) = @_;
    my $member_func = "swig_${field}_get";
    $self->$member_func();
}

sub STORE {
    my ($self,$field,$newval) = @_;
    my $member_func = "swig_${field}_set";
    $self->$member_func($newval);
}

sub this {
    my $ptr = shift;
    return tied(%$ptr);
}


# ------- FUNCTION WRAPPERS --------

package Bayesian;

*power = *Bayesianc::power;
*f = *Bayesianc::f;
*func = *Bayesianc::func;
*Bayesian = *Bayesianc::Bayesian;

# ------- VARIABLE STUBS --------

package Bayesian;

1;
