# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.40
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

package gd;
use base qw(Exporter);
use base qw(DynaLoader);
package gdc;
bootstrap gd;
package gd;
@EXPORT = qw();

# ---------- BASE METHODS -------------

package gd;

sub TIEHASH {
    my ($classname,$obj) = @_;
    return bless $obj, $classname;
}

sub CLEAR { }

sub FIRSTKEY { }

sub NEXTKEY { }

sub FETCH {
    my ($self,$field) = @_;
    my $member_func = "swig_${field}_get";
    $self->$member_func();
}

sub STORE {
    my ($self,$field,$newval) = @_;
    my $member_func = "swig_${field}_set";
    $self->$member_func($newval);
}

sub this {
    my $ptr = shift;
    return tied(%$ptr);
}


# ------- FUNCTION WRAPPERS --------

package gd;

*gdImageCreate = *gdc::gdImageCreate;
*gdImageDestroy = *gdc::gdImageDestroy;
*gdImageLine = *gdc::gdImageLine;
*gdImageColorAllocate = *gdc::gdImageColorAllocate;
*gdImageGif = *gdc::gdImageGif;
*fopen = *gdc::fopen;
*fclose = *gdc::fclose;

# ------- VARIABLE STUBS --------

package gd;

1;
